### ISSUE TITLE
Conflict between "Day of Month" & "Day of Week"

### ISSUE THREAD

**Issue by CooledCoffee** [josiahcarlson/parse-crontab#13]
Cron expressions such as "0 0 1-7 * 4" (first thursday of every month) is not supported by your library.
The error is caused by these code:

        if not matchers.day.any:
            _assert(matchers.weekday.any,
                "missing a wildcard specifier for weekday")
        if not matchers.weekday.any:
            _assert(matchers.day.any,
                "missing a wildcard specifier for day")

in the CronTab._make_matchers method.

**Comment by josiahcarlson** [comment]
As @grahambell mentioned, the '#' specifier is supposed to handle that behavior, but this module explicitly excludes that functionality. And as @grahambell quoted, when both day of month and week are restricted, cron expressions don't work the way you would expect.

To address this limitation, I would suggest using the "0 0 1-7 * *" variant, then verifying upon trigger that the date/time is on the day of week that you want. I do a similar thing to handle timezones and DST changes in my own code that uses this package.
