### ISSUE TITLE
Please install process in readme.md

### ISSUE THREAD

**Issue by rfyiamcool** [josiahcarlson/parse-crontab#14]
Please install process in readme.md
then, pip install crontab

**Comment by josiahcarlson** [comment]
I don't understand what you are asking for.

**Comment by josiahcarlson** [comment]
Can you describe what you want in a different way?

**Comment by Skeen** [comment]
Probably just wants an installation guide in the README file, something alike:

# Install
```
pip install crontab
```

**Comment by josiahcarlson** [comment]
Done.
