### ISSUE TITLE
Incorrect example: `* 3 * * *`

### ISSUE THREAD

**Issue by siemanko** [josiahcarlson/parse-crontab#21]
**What we wish had happened?**
when using string `* 3 * * *` we should run the job every minute between 3 and 4 am. 

**What actually happens?**
job runs every minute.

**Comment by josiahcarlson** [comment]
Can you show an actual example? Because when I test this, it works just fine:

```
>>> from crontab import CronTab
>>> a = CronTab('* 3 * * *')
>>> from datetime import datetime
>>> a.next(datetime(2017, 1, 31, 2), default_utc=True)
3600.0
>>> a.next(datetime(2017, 1, 31, 2, 30), default_utc=True)
1800.0
>>> a.next(datetime(2017, 1, 31, 3, 0), default_utc=True)
60.0
>>> a.next(datetime(2017, 1, 31, 2, 59), default_utc=True)
60.0
>>> a.next(datetime(2017, 1, 31, 2, 50), default_utc=True)
600.0
>>> a.next(datetime(2017, 1, 31, 3, 59), default_utc=True)
82860.0
>>> a.next(datetime(2017, 1, 31, 3, 58), default_utc=True)
60.0
```

**Comment by josiahcarlson** [comment]
Or are you using some other library's implementation, but using this library's examples?

**Comment by nivwusquorum** [comment]
Yes, I am using pip installable version, is that not you?

**Comment by nivwusquorum** [comment]
It has the same API...

**Comment by josiahcarlson** [comment]
Can you execute the things that I have provided? Can you show an example where it doesn't work the way I have shown? Can you write a unittest that demonstrates the issue?

**Comment by josiahcarlson** [comment]
Also, when you say "I am using pip installable version, is that not you?", I don't know! Can you provide a link to the package you download and installed? Can you show the output of `vars(crontab)`?
