### ISSUE TITLE
How to Stop Cron Daemon from Sending Email for Each Job

### ISSUE THREAD

**Issue by shinokada** [josiahcarlson/parse-crontab#37]
I get a mail notice after the cron job.
I edit the cronjob by adding `2>&1` to avoid this.
But is there any way I can stop sending an email for each job from cronTab?

```
15 10 * * * bash /Users/shinokada/Cron/daily_bubu >/dev/null 2>&1
# bubu

0 10 2-30/2 * * bash /Users/shinokada/Cron/cleanit_job>/dev/null 2>&1
# daily_clean
```

![image](https://user-images.githubusercontent.com/147320/114343579-1d5f0480-9b99-11eb-90b8-2245c5d0b54a.png)

**Comment by josiahcarlson** [comment]
Hello @shinokada , my library is not used or called by linux or other system `crontab` utilities. It's mostly used by Python modules to interact with cron-like schedules.

But to answer your question, I believe if you set `MAILTO=""` above your schedules in `crontab -e`, you shouldn't be getting emails. If that doesn't work, I don't know. Your crontab daemon must be weird. I'd contact the author, by checking `man crontab`.
