### ISSUE TITLE
0/15 * * * * cron spec is valid cron string but centos is not able to create a crontab entry with freq '0/15 * * *  *'

### ISSUE THREAD

**Issue by ashvarma1982** [josiahcarlson/parse-crontab#42]
So for cron spec frequency '0/15 * * * *' is a valid cron string as per parse-crontab but centos rejects it as per the crontab specification.

As Per the crontab(5) man page on CentOS 7,Step  values can be used in conjunction with ranges andStep values are also permitted after an asterisk. The /15 is a step value and since the 0 in 0/15 is neither a range nor an asterisk, the crontab Linux utility rejects it.

Such an error results in failure for updating cronjobs trying to set with this cron frequency.

**Comment by ashvarma1982** [comment]
'0/15 * * * *' should not be valid 
```
>>> _= CronTab('0/15 * * * *')
>>> _
<crontab._crontab.CronTab object at 0x7f627ff8ce18>
```

**Comment by josiahcarlson** [comment]
This library is not a Crontab validator for the spec, nor is it the scheduling library for Centos; this is a scheduling library for Python software.

This specific schedule variation, `<start>/<step>`, is being used in at least 5 different commercial codebases that I've added it to (one of which protects a huge swath of the internet), and at least one is an online service provider for DBT, as I've used online tools that accept my `<start>/<step>` schedule. Which makes me believe that either other software has my same (reasonable) interpretation, or others (including myself) are necessarily using my software the way I intended it.

If you need validation, you can do a 2nd step if Crontab doesn't complain:
`re.search("[^-]/", re.sub("-+", "-", re.sub("[0-9,]+-[0-9,]+", "-", SCHEDULE))`

That regular expression will return a match if the user didn't use a range:
```
>>> re.search("[^-]/", re.sub("-+", "-", re.sub("[0-9,]+-[0-9,]+", "-", "0-8 0/15 8-9/15")))
<_sre.SRE_Match object; span=(2, 4), match='0/'>
>>> re.search("[^-]/", re.sub("-+", "-", re.sub("[0-9,]+-[0-9,]+", "-", "0-8 0-9/15 8-9/15")))
>>> 
```

I'll go ahead and update the Wiki article to provide information about this crontab variation.
